services:
  # ===================================================================================================================================================================================
  backend:
    image: lunisoft/zelty-db:backend
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
      - DISPLAY=${X11_DISPLAY}
      - APP_PORT=${APP_PORT}
      - APP_BASE_URL=${APP_BASE_URL}
      - APP_DATABASE_CONNECTION_URL=${APP_DATABASE_CONNECTION_URL}
      - APP_REDIS_HOST=${APP_REDIS_HOST}
      - APP_REDIS_PORT=${APP_REDIS_PORT}
      - API_ZELTY_KEY=${API_ZELTY_KEY}
    volumes:
      - ./backend/logs:/usr/src/app/logs
    depends_on:
      - postgres
      - redis
    tty: true
    restart: unless-stopped
  # ===================================================================================================================================================================================
  caddy:
    image: lunisoft/zelty-db:caddy
    build:
      context: ./caddy
    volumes:
      - ./caddy/logs:/var/log/caddy:z
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend
    restart: unless-stopped
  # ===================================================================================================================================================================================
  redis:
    image: redis:8.2.2
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    restart: unless-stopped
  # ===================================================================================================================================================================================
  postgres:
    image: postgres:17.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=lunisoft
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${PROJECT_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  caddy_data:
  caddy_config:
